package fh.swf.enums;

public enum Instruments {
    TITLE_1("Piano"),
    ACOUSTIC_GRAND_PIANO("Acoustic Grand Piano", 0),
    BRIGHT_ACOUSTIC_PIANO("Bright Acoustic Piano", 1),
    ELECTRIC_GRAND_PIANO("Electric Grand Piano", 2),
    HONKY_TONK_PIANO("Honky-tonk Piano", 3),
    ELECTRIC_PIANO_1("Electric Piano 1", 4),
    ELECTRIC_PIANO_2("Electric Piano 2", 5),
    HARPSICHORD("Harpsichord", 6),
    CLAVI("Clavi", 7),
    TITLE_2("Chromatic Percussion"),
    CELESTA("Celesta", 8),
    GLOCKENSPIEL("Glockenspiel", 9),
    MUSIC_BOX("Music Box", 10),
    VIBRAPHONE("Vibraphone", 11),
    MARIMBA("Marimba", 12),
    XYLOPHONE("Xylophone", 13),
    TUBULAR_BELLS("Tubular Bells", 14),
    DULCIMER("Dulcimer", 15),
    TITLE_3("Organ"),
    DRAWBAR_ORGAN("Drawbar Organ", 16),
    PERCUSSIVE_ORGAN("Percussive Organ", 17),
    ROCK_ORGAN("Rock Organ", 18),
    CHURCH_ORGAN("Church Organ", 19),
    REED_ORGAN("Reed Organ", 20),
    ACCORDION("Accordion", 21),
    HARMONICA("Harmonica", 22),
    TANGO_ACCORDION("Tango Accordion", 23),
    TITLE_4("Guitar"),
    ACOUSTIC_GUITAR_NYLON("Acoustic Guitar (nylon)", 24),
    ACOUSTIC_GUITAR_STEEL("Acoustic Guitar (steel)", 25),
    ELECTRIC_GUITAR_JAZZ("Electric Guitar (jazz)", 26),
    ELECTRIC_GUITAR_CLEAN("Electric Guitar (clean)", 27),
    ELECTRIC_GUITAR_MUTED("Electric Guitar (muted)", 28),
    OVERDRIVEN_GUITAR("Overdriven Guitar", 29),
    DISTORTION_GUITAR("Distortion Guitar", 30),
    GUITAR_HARMONICS("Guitar Harmonics", 31),
    TITLE_5("Bass"),
    ACOUSTIC_BASS("Acoustic Bass", 32),
    ELECTRIC_BASS_FINGER("Electric Bass (finger)", 33),
    ELECTRIC_BASS_PICK("Electric Bass (pick)", 34),
    FRETLESS_BASS("Fretless Bass", 35),
    SLAP_BASS_1("Slap Bass 1", 36),
    SLAP_BASS_2("Slap Bass 2", 37),
    SYNTH_BASS_1("Synth Bass 1", 38),
    SYNTH_BASS_2("Synth Bass 2", 39),
    TITLE_6("Strings"),
    VIOLIN("Violin", 40),
    VIOLA("Viola", 41),
    CELLO("Cello", 42),
    CONTRABASS("Contrabass", 43),
    TREMOLO_STRINGS("Tremolo Strings", 44),
    PIZZICATO_STRINGS("Pizzicato Strings", 45),
    ORCHESTRAL_HARP("Orchestral Harp", 46),
    TIMPANI("Timpani", 47),
    TITLE_7("Ensemble"),
    STRING_ENSEMBLE_1("String Ensemble 1", 48),
    STRING_ENSEMBLE_2("String Ensemble 2", 49),
    SYNTHSTRINGS_1("SynthStrings 1", 50),
    SYNTHSTRINGS_2("SynthStrings 2", 51),
    CHOIR_AAHS("Choir Aahs", 52),
    VOICE_OOHS("Voice Ooohs", 53),
    SYNTH_VOICE("Synth Voice", 54),
    ORCHESTRA_HIT("Orchestra Hit", 55),
    TITLE_8("Brass"),
    TRUMPET("Trumpet", 56),
    TROMBONE("Trombone", 57),
    TUBA("Tuba", 58),
    MUTED_TRUMPET("Muted Trumpet", 59),
    FRENCH_HORN("French Horn", 60),
    BRASS_SECTION("Brass Section", 61),
    SYNTHBRASS_1("SynthBrass 1", 62),
    SYNTHBRASS_2("SynthBrass 2", 63),
    TITLE_9("Reed"),
    SOPRANO_SAX("Soprano Sax", 64),
    ALTO_SAX("Alto Sax", 65),
    TENOR_SAX("Tenor Sax", 66),
    BARITONE_SAX("Baritone Sax", 67),
    OBOE("Oboe", 68),
    ENGLISH_HORN("English Horn", 69),
    BASSOON("Bassoon", 70),
    CLARINET("Clarinet", 71),
    TITLE_10("Pipe"),
    PICCOLO("Piccolo", 72),
    FLUTE("Flute", 73),
    RECORDER("Recorder", 74),
    PAN_FLUTE("Pan Flute", 75),
    BLOWN_BOTTLE("Blown Bottle", 76),
    SHAKUHACHI("Shakuhachi", 77),
    WHISTLE("Whistle", 78),
    OCARINA("Ocarina", 79),
    TITLE_11("Synth Lead"),
    LEAD_1_SQUARE("Lead 1 (square)", 80),
    LEAD_2_SAWTOOTH("Lead 2 (sawtooth)", 81),
    LEAD_3_CALLIOPE("Lead 3 (calliope)", 82),
    LEAD_4_CHIFF("Lead 4 (chiff)", 83),
    LEAD_5_CHARANG("Lead 5 (charang)", 84),
    LEAD_6_VOICE("Lead 6 (voice)", 85),
    LEAD_7_FIFTHS("Lead 7 (fifths)", 86),
    LEAD_8_BASS_LEAD("Lead 8 (bass + lead)", 87),
    TITLE_12("Synth Pad"),
    PAD_1_NEW_AGE("Pad 1 (new age)", 88),
    PAD_2_WARM("Pad 2 (warm)", 89),
    PAD_3_POLYSYNTH("Pad 3 (polysynth)", 90),
    PAD_4_CHOIR("Pad 4 (choir)", 91),
    PAD_5_BOWED("Pad 5 (bowed)", 92),
    PAD_6_METALLIC("Pad 6 (metallic)", 93),
    PAD_7_HALO("Pad 7 (halo)", 94),
    PAD_8_SWEEP("Pad 8 (sweep)", 95),
    TITLE_13("Synth Effects"),
    FX_1_RAIN("FX 1 (rain)", 96),
    FX_2_SOUNDTRACK("FX 2 (soundtrack)", 97),
    FX_3_CRYSTAL("FX 3 (crystal)", 98),
    FX_4_ATMOSPHERE("FX 4 (atmosphere)", 99),
    FX_5_BRIGHTNESS("FX 5 (brightness)", 100),
    FX_6_GOBLINS("FX 6 (goblins)", 101),
    FX_7_ECHOES("FX 7 (echoes)", 102),
    FX_8_SCI_FI("FX 8 (sci-fi)", 103),
    TITLE_14("Ethnic"),
    SITAR("Sitar", 104),
    BANJO("Banjo", 105),
    SHAMISEN("Shamisen", 106),
    KOTO("Koto", 107),
    KALIMBA("Kalimba", 108),
    BAGPIPE("Bagpipe", 109),
    FIDDLE("Fiddle", 110),
    SHANAI("Shanai", 111),
    TITLE_15("Percussive"),
    TINKLE_BELL("Tinkle Bell", 112),
    AGOGO("Agogo", 113),
    STEEL_DRUM("Steel Drums", 114),
    WOODBLOCK("Woodblock", 115),
    TAIKO_DRUM("Taiko Drum", 116),
    MELODIC_TOM("Melodic Tom", 117),
    SYNTH_DRUM("Synth Drum", 118),
    REVERSE_CYMBAL("Reverse Cymbal", 119),
    GUITAR_FRET_NOISE("Guitar Fret Noise", 120),
    TITLE_16("Sound Effects"),
    BREATH_NOISE("Breath Noise", 121),
    SEASHORE("Seashore", 122),
    BIRD_TWEET("Bird Tweet", 123),
    TELEPHONE_RING("Telephone Ring", 124),
    HELICOPTER("Helicopter", 125),
    APPLAUSE("Applause", 126),
    GUNSHOT("Gunshot", 127),
    TITLE_17("Drums", -1),
    DRUMS("Drums", 200);

    private final String name;
    private final int num;

    Instruments(String name, int num) {
        this.name = name;
        this.num = num;
    }

    Instruments(String name) {
        this(name, -1);
    }

    public String getName() {
        return name;
    }
    public int getNum() {
        return num;
    }
}
